### ISSUE TITLE
Provide more comfortable subscribe and unsubscribe methods

### ISSUE THREAD

**Issue by codechimp** [zalando/nakadi-klients#74]
```
 <T extends Event> Optional<ClientError> subscribe(String eventTypeName, StreamParameters parameters, Listener<T> listener, TypeReference<EventStreamBatch<T>> typeRef);
```

This fits for Scala code. In Java, everyone assumes an exception, if something went wrong.

```
void unsubscribe(String eventTypeName,Optional<String> partition, Listener<T> listener);
```

This can be quite unhandy, if you are not subscribed to specific partitions. btw: how do I know to which partitions I am subscribed?

please provide
```
void unsubscribe(String eventTypeName, Listener<T> listener);
void unsubscribe(String eventTypeName);
```

**Comment by kanuku** [comment]
@codechimp  You have a point when it comes to unexpected cases. If an exception occurs in the implementation of the client, it will not be caught but it will rather bobble up the call hierarchy.   
For communicating possible errors that can happen after i.e.: unsubscribing a listener from a subscription that does not exist. Here I think it would make sense to return the ClientError object with some information about the result of the attempt. This information could be accessed by the caller if necessary, but it will not be obligatory because the client is already logging those errors.  

The method `unsubscribe` will be changed to return an `Optional<ClientError>` that can be used to communicate unexpected but handleable cases. This is also more in line with the approach implemented throughout the whole API.

```java
<T extends Event> Optional<ClientError> unsubscribe(String eventTypeName,Optional<String> partition, Listener<T> listener);
```
